language: python

python:
  - "2.7"

# command to install dependencies
install: 
  -  pip install -r books/requirements.txt --use-mirrors
  -  pip install coveralls --use-mirrors

# command to run tests
script: 
  -  coverage run --source="." books/manage.py test mylibrary

after_success:
  - coveralls  
